import { createIssue, listIssues, readIssue } from './dist/tools/issues.js';

async function test() {
  process.argv[2] = '../'; // point to the root AgnosticIssuer folder which has .quill.md
  
  console.log('--- Creating Issue ---');
  const res = await createIssue('Test from MCP', 'task', 'open', 'This is a test issue generated by MCP.', undefined);
  console.log(res.content[0].text);
  
  console.log('\n--- Listing Issues ---');
  const list = await listIssues();
  console.log(list.content[0].text.substring(0, 500) + '...');
  
}

test().catch(console.error);
