import fs from 'node:fs';
import path from 'node:path';

const markdownPath = path.resolve('docs/agile-frameworks-research.md');
const outputPath = path.resolve('src/lib/services/framework-presets.ts');

const content = fs.readFileSync(markdownPath, 'utf8');
const lines = content.split('\n');

const frameworks = [];
let currentFramework = null;
let currentTemplate = null;
let currentJson = [];
let parsingMode = null; // 'config' | 'template' | null

for (let i = 0; i < lines.length; i++) {
	const line = lines[i];

	// Match framework heading: ### 4.1 Scrum (...)
	const frameworkMatch = line.match(/^###\s+\d+\.\d+\s+(.+)$/);
	if (frameworkMatch) {
		currentFramework = {
			id: '',
			name: frameworkMatch[1].split('(')[0].trim().replace(/—.*$/, '').trim(),
			description: '',
			config: null,
			templates: []
		};
		// generate an ID from the name
		currentFramework.id = currentFramework.name
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, '-')
			.replace(/(^-|-$)/g, '');
		frameworks.push(currentFramework);
		parsingMode = null;
		continue;
	}

	if (!currentFramework) continue;

	// Extract description (Essence)
	if (line.startsWith('**Essence.**')) {
		currentFramework.description = line.replace('**Essence.**', '').trim();
		continue;
	}

	// Match config heading: #### 4.1.1 `config.json`
	if (line.match(/^####\s+\d+\.\d+\.\d+\s+`config\.json`/)) {
		parsingMode = 'config';
		continue;
	}

	// Match template heading: #### 4.1.2 `templates/epic.json`
	const templateMatch = line.match(/^####\s+\d+\.\d+\.\d+\s+`templates\/([^`]+)`/);
	if (templateMatch) {
		parsingMode = 'template';
		currentTemplate = { name: templateMatch[1] };
		continue;
	}

	// Read JSON blocks
	if (line.startsWith('```json')) {
		currentJson = [];
		let j = i + 1;
		while (j < lines.length && !lines[j].startsWith('```')) {
			currentJson.push(lines[j]);
			j++;
		}

		const jsonString = currentJson.join('\n');
		try {
			const parsed = JSON.parse(jsonString);
			if (parsingMode === 'config') {
				currentFramework.config = parsed;
			} else if (parsingMode === 'template' && currentTemplate) {
				currentFramework.templates.push(parsed);
			}
		} catch (e) {
			console.error(
				`Failed to parse JSON for ${currentFramework.name} in mode ${parsingMode}:`,
				e.message
			);
		}

		i = j; // skip to end of json block
		parsingMode = null;
	}
}

// Filter valid frameworks (those that have a config and templates)
const validFrameworks = frameworks.filter((f) => f.config !== null && f.templates.length > 0);

// Resolve template inheritance (scaling frameworks use Scrum templates)
const scrum = validFrameworks.find((f) => f.id === 'scrum');
if (scrum) {
	const epicT = scrum.templates.find((t) => t.id === 'epic');
	const storyT = scrum.templates.find((t) => t.id === 'user-story');
	const taskT = scrum.templates.find((t) => t.id === 'task');
	const bugT = scrum.templates.find((t) => t.id === 'bug');
	const baseScrumT = [epicT, storyT, taskT, bugT].filter(Boolean);

	const injectTo = (id, tmpls) => {
		const fw = validFrameworks.find((f) => f.id === id);
		if (fw) {
			const existingIds = fw.templates.map((t) => t.id);
			const toAdd = tmpls.filter((t) => !existingIds.includes(t.id));
			// Insert base templates at the beginning
			fw.templates.unshift(...toAdd);
		}
	};

	injectTo('large-scale-scrum', baseScrumT);
	injectTo('nexus', baseScrumT);
	injectTo('scrum-scale', baseScrumT);
	injectTo('water-scrum-fall', [storyT]);
	injectTo('scrumban', [storyT, taskT]);
}

// Generate TS file
const tsHeader = `/**
 * Auto-generated by scripts/extract-presets.mjs from docs/agile-frameworks-research.md
 * Do not edit this file manually.
 */

import type { Config, Template } from '../types/index.ts';

export interface FrameworkPreset {
	id: string;
	name: string;
	description: string;
	config: Config;
	templates: Template[];
}

export const FRAMEWORK_PRESETS: FrameworkPreset[] = 
`;

const tsFooter = `;\n`;

fs.writeFileSync(outputPath, tsHeader + JSON.stringify(validFrameworks, null, '\t') + tsFooter);
console.log(`Successfully extracted ${validFrameworks.length} frameworks to ${outputPath}`);
