import fs from 'node:fs';

const enStrings = JSON.parse(fs.readFileSync('scripts/en-strings.json', 'utf8'));
const esDict = { ...enStrings };

// A function to easily replace keys
function set(en, es) {
    if (en in esDict) {
        esDict[en] = es;
    }
}

// Map common short strings
const common = {
    "Scrum": "Scrum",
    "Build and ship increments of value that meet the Definition of Done every Sprint.": "Construir y entregar incrementos de valor que cumplan la Definición de Hecho en cada Sprint.",
    "Code is peer-reviewed and merged to the trunk.": "El código es revisado por pares y fusionado en la rama principal.",
    "Unit tests pass and coverage meets the team threshold.": "Las pruebas unitarias pasan y la cobertura cumple el umbral del equipo.",
    "Acceptance criteria from the user story are checked end-to-end.": "Los criterios de aceptación de la historia de usuario se verifican de principio a fin.",
    "Documentation is updated where the user-visible behaviour changed.": "La documentación se actualiza donde cambió el comportamiento visible para el usuario.",
    "Build is deployable to staging without manual intervention.": "La compilación es desplegable a staging sin intervención manual.",
    "Open (Product Backlog)": "Abierto (Product Backlog)",
    "Ready for Sprint": "Listo para Sprint",
    "In progress": "En progreso",
    "In review": "En revisión",
    "Done (Sprint Increment)": "Hecho (Incremento del Sprint)",
    "Closed": "Cerrado",
    "Removed (out of Sprint)": "Removido (fuera del Sprint)",
    "Epic": "Épica",
    "Business value": "Valor de negocio",
    "Target release": "Lanzamiento objetivo",
    "User Story": "Historia de Usuario",
    "Story points": "Puntos de historia",
    "Priority": "Prioridad",
    "Sprint": "Sprint",
    "Assignee": "Responsable",
    "Labels": "Etiquetas",
    "Task": "Tarea",
    "Estimate (hours)": "Estimación (horas)",
    "Bug": "Bug (Error)",
    "Severity": "Severidad",
    "Regression from": "Regresión desde",
    "Kanban": "Kanban",
    "Optimise the flow of work through the team with predictable cycle time and bounded WIP.": "Optimizar el flujo de trabajo del equipo con un tiempo de ciclo predecible y WIP limitado.",
    "Work item is checked end-to-end by the person who pulled it.": "El ítem de trabajo es verificado de principio a fin por la persona que lo tomó.",
    "Card satisfies the column's exit policy (definition of ready / done).": "La tarjeta cumple con la política de salida de la columna (definición de listo / hecho).",
    "Lead time and cycle time are recorded automatically.": "El lead time y cycle time se registran automáticamente.",
    "Backlog": "Backlog",
    "Ready (pullable)": "Listo (para tomar)",
    "Review": "Revisión",
    "Blocked": "Bloqueado",
    "Done": "Hecho",
    "Cancelled": "Cancelado",
    "Request": "Solicitud",
    "Class of service": "Clase de servicio",
    "Requester": "Solicitante",
    "Cycle time (h, computed)": "Tiempo de ciclo (h, calculado)",
    "Extreme Programming": "Extreme Programming",
    "Deliver valuable software through disciplined engineering practices, tight feedback loops, and a present customer.": "Entregar software valioso a través de prácticas de ingeniería disciplinadas, ciclos de retroalimentación cortos y un cliente presente.",
    "Story is covered by an automated acceptance test that passes.": "La historia está cubierta por una prueba de aceptación automatizada que pasa.",
    "All unit tests pass; coverage meets the team threshold.": "Todas las pruebas unitarias pasan; la cobertura cumple el umbral del equipo.",
    "Code has been pair-reviewed and merged to trunk (CI green).": "El código ha sido revisado en pares y fusionado a trunk (CI en verde).",
    "Story is demonstrated to the on-site customer.": "La historia es demostrada al cliente in situ.",
    "Open (Story card)": "Abierto (Tarjeta de Historia)",
    "Estimated (Story Game)": "Estimado (Juego de Historias)",
    "Committed (Iteration)": "Comprometido (Iteración)",
    "Acceptance test pass": "Prueba de aceptación pasa",
    "Merged (CI green)": "Fusionado (CI en verde)",
    "Abandoned": "Abandonado",
    "Ideal weeks": "Semanas ideales",
    "Risk index": "Índice de riesgo",
    "Volatility (likely to change)": "Volatilidad (probable a cambiar)",
    "Owner": "Propietario",
    "Engineering Task": "Tarea de Ingeniería",
    "Ideal hours": "Horas ideales",
    "Volunteer": "Voluntario",
    "Pair with": "Emparejar con",
    "Spike": "Spike",
    "Timebox (hours)": "Timebox (horas)",
    "Question to answer": "Pregunta a responder",
    "Spike owner": "Propietario del spike",
    "Defect": "Defecto",
    "Failing test path": "Ruta de prueba que falla",
    "Lean Software Development": "Lean Software Development",
    "Deliver maximum customer value with minimum waste by optimising the entire value stream.": "Entregar el máximo valor al cliente con el mínimo desperdicio optimizando todo el flujo de valor.",
    "Value item is verified by the customer.": "El ítem de valor es verificado por el cliente.",
    "Waste item has a root cause and a countermeasure.": "El ítem de desperdicio tiene una causa raíz y una contramedida.",
    "Kaizen has measurable before/after metrics.": "Kaizen tiene métricas medibles antes/después.",
    "Identified": "Identificado",
    "Analysing": "Analizando",
    "Validating": "Validando",
    "Rejected (not value)": "Rechazado (sin valor)",
    "Value Item": "Ítem de Valor",
    "Value stream": "Flujo de valor",
    "Customer value": "Valor para el cliente",
    "Lead time (days)": "Lead time (días)",
    "Waste Item": "Ítem de Desperdicio",
    "Waste type": "Tipo de desperdicio",
    "Stage in value stream": "Etapa en flujo de valor",
    "Kaizen": "Kaizen",
    "Metric to improve": "Métrica a mejorar",
    "Baseline value": "Valor base",
    "Target value": "Valor objetivo",
    "Sponsor": "Patrocinador",
    "Feature-Driven Development": "Feature-Driven Development (FDD)",
    "Build the right thing right by planning and tracking against a hierarchical feature list and a domain object model.": "Construir lo correcto correctamente planificando y haciendo seguimiento contra una lista jerárquica de características y un modelo de objetos de dominio.",
    "Feature design passes design inspection.": "El diseño de la característica pasa la inspección de diseño.",
    "Feature code passes code inspection by Chief Programmer.": "El código de la característica pasa la inspección de código por el Programador Jefe.",
    "Feature is integrated into the main build.": "La característica está integrada en la compilación principal.",
    "Feature is reported as a percentage complete milestone.": "La característica se reporta como un hito de porcentaje completado.",
    "Modelling": "Modelado",
    "Feature listed": "Característica listada",
    "Planned": "Planificado",
    "Designing": "Diseñando",
    "Building": "Construyendo",
    "Inspecting": "Inspeccionando",
    "Domain Model": "Modelo de Dominio",
    "Subject area": "Área temática",
    "Chief architect": "Arquitecto Jefe",
    "Feature Set": "Conjunto de Características",
    "Feature set owner": "Propietario del conjunto",
    "Feature": "Característica",
    "Action (verb)": "Acción (verbo)",
    "Result": "Resultado",
    "Object": "Objeto",
    "Feature set": "Conjunto de características",
    "Chief programmer": "Programador Jefe",
    "Class owners (comma-separated users)": "Dueños de clase (usuarios separados por comas)",
    "Crystal family": "Familia Crystal",
    "Ship working software frequently, communicate osmotically, and reflect every cycle.": "Entregar software funcionando frecuentemente, comunicarse osmóticamente y reflexionar cada ciclo.",
    "Deliverable is integrated and demoed to a sponsor.": "El entregable está integrado y demostrado a un patrocinador.",
    "Reflection workshop updates the next cycle's plan.": "El taller de reflexión actualiza el plan del siguiente ciclo.",
    "Each team member is safe to raise any concern.": "Cada miembro del equipo está seguro para plantear cualquier inquietud.",
    "Waiting": "Esperando",
    "Next": "Siguiente",
    "Now": "Ahora",
    "Delivery": "Entrega",
    "Dropped": "Descartado",
    "Deliverable": "Entregable",
    "Crystal colour": "Color de Crystal",
    "Comfort / D-class": "Confort / Clase-D",
    "Reflection Action": "Acción de Reflexión",
    "From workshop": "Del taller",
    "DSDM / Atern / Agile Project Framework": "DSDM / Atern / Agile Project Framework",
    "Deliver the right business solution on time, to fixed quality, with explicit MoSCoW prioritisation inside every timebox.": "Entregar la solución de negocio correcta a tiempo, con calidad fija y priorización MoSCoW explícita dentro de cada timebox.",
    "Requirement meets its acceptance criteria and MoSCoW priority is recorded.": "El requisito cumple sus criterios de aceptación y se registra su prioridad MoSCoW.",
    "Solution is reviewed in a timebox review workshop.": "La solución se revisa en un taller de revisión del timebox.",
    "Test evidence is filed with the timebox deliverable.": "La evidencia de prueba se archiva con el entregable del timebox.",
    "Feasibility": "Factibilidad",
    "Foundations": "Fundamentos",
    "Exploratory": "Exploratorio",
    "Engineering": "Ingeniería",
    "Timebox review": "Revisión del timebox",
    "Deployed": "Desplegado",
    "Won't (this time)": "Won't (esta vez)",
    "Requirement": "Requisito",
    "MoSCoW priority": "Prioridad MoSCoW",
    "Timebox": "Timebox",
    "Business need": "Necesidad de negocio",
    "Start": "Inicio",
    "End (fixed)": "Fin (fijo)",
    "Lifecycle phase": "Fase de ciclo de vida",
    "Timebox lead": "Líder de Timebox",
    "Model": "Modelo",
    "Workshop date": "Fecha de taller",
    "Facilitator": "Facilitador"
};

Object.entries(common).forEach(([k, v]) => set(k, v));

fs.writeFileSync('scripts/es-dict-1.json', JSON.stringify(esDict, null, '\t'));
