import fs from 'node:fs';

const esDict = JSON.parse(fs.readFileSync('scripts/es-dict-1.json', 'utf8'));

function set(en, es) {
    if (en in esDict) {
        esDict[en] = es;
    }
}

const common2 = {
    "Scrumban": "Scrumban",
    "Maintain a continuous, flow-optimised delivery cadence, planning on demand when the Ready queue is depleted.": "Mantener una cadencia de entrega continua y optimizada para el flujo, planificando a demanda cuando la cola de Listos se agote.",
    "Item has been peer-reviewed.": "El ítem ha sido revisado por pares.",
    "All tests are green on main.": "Todas las pruebas están en verde en la rama principal.",
    "Item is demonstrable end-to-end.": "El ítem es demostrable de principio a fin.",
    "Bucket · 12 months": "Cubo · 12 meses",
    "Bucket · 6 months": "Cubo · 6 meses",
    "Bucket · 3 months": "Cubo · 3 meses",
    "Ready (trigger queue)": "Listo (cola desencadenante)",
    "Bucket": "Cubo",
    "Value score": "Puntaje de valor",
    "Size": "Tamaño",
    "Shape Up": "Shape Up",
    "Ship meaningful work on a fixed 6-week cycle, betting on shaped projects and killing work that misses the circuit breaker.": "Entregar trabajo significativo en un ciclo fijo de 6 semanas, apostando a proyectos moldeados y eliminando el trabajo que supera el interruptor de circuito.",
    "Pitch is shaped to the right level of abstraction.": "El pitch está moldeado al nivel correcto de abstracción.",
    "Betting table has committed the appetite for the cycle.": "La mesa de apuestas ha comprometido el apetito para el ciclo.",
    "Build team has integrated end-to-end and the feature is in production.": "El equipo de construcción ha integrado de principio a fin y la característica está en producción.",
    "Post-cycle retro decides: keep, kill, or pitch v2 for next cycle.": "La retro retrospectiva post-ciclo decide: mantener, eliminar o pitch v2 para el próximo ciclo.",
    "Raw idea": "Idea cruda",
    "Shaping": "Moldeando",
    "Shaped (ready to bet)": "Moldeado (listo para apostar)",
    "Bet (in cycle)": "Apostado (en ciclo)",
    "Cool-down": "Enfriamiento",
    "Shipped": "Entregado",
    "Killed (no ship)": "Eliminado (sin entrega)",
    "Pitch": "Pitch",
    "Appetite (weeks)": "Apetito (semanas)",
    "Shaper": "Moldeador (Shaper)",
    "Cycle kind": "Tipo de ciclo",
    "Hill Chart Task": "Tarea del Hill Chart",
    "Hill position": "Posición en la colina",
    "Scope": "Alcance",
    "SAFe 6.0": "SAFe 6.0",
    "Deliver value continuously through Agile Release Trains aligned to a quarterly Program Increment.": "Entregar valor continuamente a través de Trenes de Liberación Ágil alineados a un Incremento de Programa trimestral.",
    "User story meets acceptance criteria and Built-in Quality practices are applied.": "La historia de usuario cumple los criterios de aceptación y se aplican prácticas de Calidad Incorporada.",
    "Feature is integrated and demonstrated in the Solution Demo.": "La característica está integrada y demostrada en la Demo de la Solución.",
    "PI objectives are reviewed in Inspect & Adapt.": "Los objetivos del PI se revisan en Inspeccionar y Adaptar.",
    "Funnel": "Embudo",
    "Analyzing": "Analizando",
    "Program Backlog": "Backlog del Programa",
    "Implementing": "Implementando",
    "Validating on Staging": "Validando en Staging",
    "Deploying to Production": "Desplegando a Producción",
    "Releasing": "Liberando",
    "Done": "Hecho",
    "Feature (SAFe)": "Característica (SAFe)",
    "WSJF Score": "Puntaje WSJF",
    "Program Increment": "Incremento de Programa (PI)",
    "Agile Release Train": "Tren de Liberación Ágil",
    "Enabler": "Habilitador",
    "Enabler type": "Tipo de habilitador",
    "LeSS": "LeSS (Large-Scale Scrum)",
    "Deliver a single whole-product Increment per Sprint using multiple teams working from one Product Backlog.": "Entregar un solo Incremento del producto completo por Sprint utilizando múltiples equipos que trabajan desde un solo Product Backlog.",
    "Code is integrated continuously into the shared trunk.": "El código se integra continuamente en la rama compartida.",
    "Feature is demonstrable in the overall product Review.": "La característica es demostrable en la Revisión general del producto.",
    "Code is covered by automated component tests.": "El código está cubierto por pruebas automatizadas de componentes.",
    "Product Backlog": "Product Backlog",
    "Sprint Backlog (Team A)": "Sprint Backlog (Equipo A)",
    "Sprint Backlog (Team B)": "Sprint Backlog (Equipo B)",
    "Done (Product Increment)": "Hecho (Incremento de Producto)",
    "Requirement (LeSS)": "Requisito (LeSS)",
    "Feature Team": "Equipo de Características",
    "Area": "Área",
    "Nexus": "Nexus",
    "Deliver an integrated Nexus Increment every Sprint by managing cross-team dependencies through the Nexus Integration Team.": "Entregar un Incremento Nexus integrado cada Sprint gestionando las dependencias entre equipos a través del Equipo de Integración Nexus.",
    "Dependencies are identified and resolved before pulling into the Sprint.": "Las dependencias son identificadas y resueltas antes de incorporarlas al Sprint.",
    "Code is integrated into the shared Nexus build.": "El código está integrado en la compilación Nexus compartida.",
    "Nexus Increment passes the Nexus Definition of Done.": "El Incremento Nexus pasa la Definición de Hecho Nexus.",
    "Nexus Backlog": "Backlog de Nexus",
    "Refining (Cross-team)": "Refinando (Inter-equipo)",
    "Ready (Unblocked)": "Listo (Desbloqueado)",
    "In Sprint (Team A)": "En Sprint (Equipo A)",
    "In Sprint (Team B)": "En Sprint (Equipo B)",
    "Integrating": "Integrando",
    "Done (Nexus Increment)": "Hecho (Incremento Nexus)",
    "Nexus Backlog Item": "Ítem del Backlog Nexus",
    "Cross-team dependency": "Dependencia inter-equipo",
    "Nexus Integration Team": "Equipo de Integración Nexus"
};

Object.entries(common2).forEach(([k, v]) => set(k, v));

fs.writeFileSync('scripts/es-dict.json', JSON.stringify(esDict, null, '\t'));
